patch: Replace balenalib with Docker Official image
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -1,10 +1,6 @@
-ARG BALENA_ARCH=%%BALENA_ARCH%%
+FROM debian:bullseye
 
-FROM balenalib/$BALENA_ARCH-debian
-ARG BALENA_ARCH=%%BALENA_ARCH%%
-
-
-RUN install_packages dnsmasq wireless-tools
+RUN apt-get update && apt-get install -y --no-install-recommends dnsmasq wireless-tools
 
 # use latest version. If specific version is required, it should be provided as vX.Y.Z, e.g v4.11.37
 ARG VERSION="latest"
@@ -16,15 +12,16 @@ WORKDIR /usr/src/app
 
 RUN \
     export BASE_URL="https://github.com/balena-os/wifi-connect/releases" &&\    
-    case $BALENA_ARCH in \
+    DETECTED_ARCH=$(uname -m) &&\
+    case $DETECTED_ARCH in \
         "aarch64") \
             BINARY_ARCH_NAME="aarch64-unknown-linux-gnu" ;; \
-        "amd64") \
+        "x86_64") \
             BINARY_ARCH_NAME="x86_64-unknown-linux-gnu" ;;\
-        "armv7hf") \
+        "armv7l") \
             BINARY_ARCH_NAME="armv7-unknown-linux-gnueabihf" ;;\
         *) \
-            echo >&2 "error: unsupported architecture ($BALENA_ARCH)"; exit 1 ;; \ 
+            echo >&2 "error: unsupported architecture ($DETECTED_ARCH)"; exit 1 ;; \ 
     esac;\
     if [ ${VERSION} = "latest" ]; then \
         export URL_PARTIAL="latest/download" ; \
